name: 报告 Bug
title: '[Bug] '
description: 报告 误触/问题 规则
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 在提交 issue 之前，请您务必确认以下信息，否则此 issue 可能会被关闭❗❗❗

        > [!WARNING]
        >   - 不要提供截图，截图对编写规则**没有任何作用❗**
        >   - 不要使用**截屏快照**

  - type: checkboxes
    id: base-info-confirm
    attributes:
      label: ✅ 请核对以下内容
      options:
        - label: 我已提供正确的**界面快照**（非截图），且在快照说明中明确标注了是哪一条规则误触/出现问题
          required: true
        - label: 如果是多次点击才能生效的情况，我已提供**每一次点击的快照**
          required: true
        - label: 我已确认使用的是 **最新版订阅** [![GitHub Release](https://img.shields.io/github/v/release/Lin-arm/GKD_subscription)](https://github.com/Lin-arm/GKD_subscription/releases/latest) 和 **最新版GKD** [![GitHub Release](https://img.shields.io/github/v/release/gkd-kit/gkd)](https://github.com/gkd-kit/gkd/releases/latest)
          required: true

  - type: checkboxes
    id: extra-confirm
    attributes:
      label: 📋 其他信息
      description: 该问题是否属于以下情况？
      options:
        - label: 规则不生效，但是截取快照/重新进入软件后生效
        - label: 规则触发了（有点击提示），但实际不生效

  - type: textarea
    id: snapshot
    attributes:
      label: |
        📸请提供 误触界面/出现问题界面 的快照（不要提供截图！！！不要使用截屏快照！！！），也可补充说明
      description: |
        快照是一个 zip 文件，快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本，按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照，上传文件或者生成链接并粘贴到下面的输入框\
        ![img](https://raw.githubusercontent.com/Lin-arm/GKD_subscription/refs/heads/main/docs/images/Snapshot.webp)
    validations:
      required: true

  - type: textarea
    id: rule
    attributes:
      label: |
        请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）
    validations:
      required: true
