name: issue_content_check
on:
  issues:
    types: [opened]
jobs:
  check-issue-content:
    runs-on: ubuntu-latest
    steps:
      - name: 缺少快照时自动标记并关闭 Issue
        if: |
          contains(github.event.issue.body, 'i.gkd.li/') == false &&
          contains(github.event.issue.body, '.zip') == false
        uses: actions/github-script@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['invalid']
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `您好 ${{ github.event.issue.user.login }}，由于您没有提供快照，此issue已被自动关闭。`
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
      - name: 快照链接不可访问时自动标记并提醒
        if: contains(github.event.issue.body, 'i.gkd.li/snapshot/') == true
        uses: actions/github-script@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['invalid']
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `您好 ${{ github.event.issue.user.login }}，检测到您提供了他人无法访问的链接，\n请点击查看 [正确的分享快照方式说明](https://gkd.li/guide/snapshot#share-note) 。\n可在下方评论区补充`
            });
